server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${hm.db.host}}:3306/west2_online_project
    username: root
    password: ${hm.db.pw}
  data:
    redis:
      host: ${hm.re.host}
      port: 6379
      password: ${hm.re.pw}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 4096MB
  mail:
    # 发送者邮箱
    username: 3525382599@qq.com
    #申请到的授权码
    password: qhttlskqpagqchja
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 端口号465或587
    port: 465
    protocol: smtps
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          auth: true
          ssl: true
          starttls:
            enable: true
            required: true

mybatis:
  configuration-properties:
    helperDialect: mysql
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true
  mapper-locations: mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true